### PR TITLE
UI tweaks

### PR DESCRIPTION
**Pull request by alistair3149**
Experimenting with some minor UI changes that help to make the site more readable and cleaner.

**Current progress**:
* Tweaked the font size and color a bit on the ship/item page.
* Tweaked item table to be a responsive design that works better on mobile while having the same layout on desktop. 

image

### CODE REVIEW

**Comment by richardthombs** [comment]
This could use a bit of rebasing now :)

**Comment by alistair3149** [comment]
The commits are pretty messed up in this one so do you prefer that I rebase this or I can make the changes again separately, but the commit will be less detailed and by file basis?

**Comment by alistair3149** [comment]
Will be re-opened in a new PR

**Comment by alistair3149** [comment]
PR reopened at #20

**Pull request closed without merging**
