### PR TITLE
Update ItemLoader.cs

### PR DESCRIPTION
**Pull request by LeMyst**
* Add all clothes items
* Add food
* Remove other stuffs

### CODE REVIEW

**Comment by richardthombs** [comment]
I think we want to have "elevator", "decal" and "display" in there, because those kinds of things do get included in ship loadouts.

**Comment by LeMyst** [comment]
I've updated the file but now I've doubt about the "drink" and "bottle" for my use.
I'll try later today.

**Comment by richardthombs** [comment]
If you need them, then by all means, please take them out of the list. The only reason I don't add everything is because it takes so long to process :)

**Comment by LeMyst** [comment]
I think the best is to create a list of types with they purpose and identify the ones needed for scunpacked and the others (if someone want to avoid them or not)

**Review by richardthombs — APPROVED** [review]

**Comment by richardthombs** [comment]
Yep, I agree. So far I just separate stuff into FPS gear on the website, but obviously that should be split out into weapons, armor, clothing etc.

**Pull request merged**
